// The "set" passages: a fixed, original block per scene type — two variants
// per scene, one picked at random per flight so repeat flights don't wear
// out. Every voice in a flight restyles the SAME block, which is what makes
// the tasting fair: beats, characters and proportions stay put, and only the
// prose style moves. Written for InkHearth — original work, no publisher
// text anywhere in this file or the passages it produces.
export const SCENE_PASSAGES = {
  action: [
    `Mara felt the hand before she heard it — a tug at her satchel, then the snap of the buckle, and the boy was already three stalls away, shoulder low, weaving through the fish-market crowd like a needle through cloth. She went after him. A crate of oranges went over; the world became ankles and shouting. He vaulted a sleeping dog, scattered pigeons off a cart, took the alley between the chandler's and the wall where the laundry lines crossed. She took it too, ducking wet sheets, boots skidding on cobbles still dark with the morning's wash. Ahead, the lane forked. He chose wrong. The second alley dead-ended at the harbor steps, and for one held breath they both looked at the water — grey, choppy, thirty feet down — then at each other. He grinned, breath ragged, her satchel slung across his chest like a trophy. Somewhere behind her the harbor watch was coming. Mara opened her hands. "You can swim," she said, "or you can explain it." The gulls, indifferent, wheeled.`,
    `The bell tower struck ten, and Ren took the roofs. Below, lanterns swung along the canal road — two of them, moving fast, the wrong fast. He ran the ridgelines instead: tile, slate, gap, tile, counting the beats like a prayer his grandmother never taught him. Behind him a shout, the scrape of a boot he felt more than heard. He leapt the dyer's court and came down hard on the counting-house roof, knees singing, and did not stop. The night was all edges — weathervanes, chapel spire, the moon caught in a wet chimney like a coin in a drain. At the tanner's he dropped into the lane, through the stink and the dark, and pressed himself into a doorway just as the lanterns reached the corner. They stopped. One of them laughed, short and ugly, and said his name like a curse. Ren counted his own heartbeats. Forty. Then the lanterns moved on toward the bridge, and he put his forehead against the cold door and breathed.`,
  ],
  grief: [
    `They found the list on Tuesday, folded into the grocery pad by the icebox, her handwriting slanting the way it always had when she was in a hurry: milk, bread, stamps, something illegible, more milk. Dev stood at the counter for a long time with the paper not moving in his hands. The kettle had gone cold twice since the funeral; the mug tree still held her yellow cup, handle turned outward the way she liked it, ready. Nobody had wanted to touch it. He poured the tea he didn't want and sat where she had sat for forty years, the chair that knew her, and read the list again. Stamps. She had still been planning stamps. Somewhere in the house a clock did what her clocks had always done, marked the hour without asking whether anyone was keeping it, and he understood, in the ordinary way that understanding arrives — not as a wave but as a chore — that he would carry this list in his wallet for the rest of his life, and that this was correct, and that it would never be enough.`,
    `The coat was still on its hook by the door, and every time a new guest arrived I expected the argument about the draft. People kept saying her name in the past tense, carefully, the way you set down a full glass. I refilled things. That was the job I had given myself: the olives, the water jug, the small mercies of the table, because grief with hands is easier than grief without. Aunt Rina caught me by the elbow and told me a story I had heard a hundred times and never once like this — how my mother, at seventeen, had talked her way onto a ferry just to see where it went. In the hallway the coat waited, collar turned up the way she wore it, one pocket heavier than the other with whatever she had decided was important that last morning. I did not go to it. I said thank you, and I mean that literally: those were the words, thank you, thank you, until the door finally closed and the house went quiet enough, at last, to be exactly as empty as it was.`,
  ],
  atmosphere: [
    `All day the light had lain on the water like a held breath, and now, at the turn of the evening, the west finally answered. The cloud came down the channel the way a carpet is unrolled — vast, deliberate, its leading edge already the colour of wet slate — and the lighthouse at the point put on its one white stare. Below the headland the tide had begun to find its voice, slapping the black rocks in a slow, considered rhythm, and the gorse bent all at once, the whole hillside combing itself in the same direction. Pelic, the last of the season's visitors, stood on the sea wall with his collar up, watching the fishing boats come in small and urgent across the darkening water. There is a quality of light that exists only in the minute before weather: too bright and too low at once, every wet stone lit from beneath, the whole harbour gilded like something remembered. Then the first drops came, fat and widely spaced, and the light was gone, and the storm had the room to itself.`,
    `Snow closed the pass on the third night, and the inn drew in on itself like a ship. By lamplight the windows became mirrors, and the common room became the whole world: six travellers, a fire that had to be fed or the world would end, the landlady's knitting needles keeping a time no clock would admit to. Outside, the silence had a texture — not an absence but a pressure, the kind that makes you speak softly in your own house. The wind tested the shutters at intervals, polite at first, then less so. Every traveller listened to it in their own language of stillness: the peddler counted his coins; the soldier watched the door without watching it; the girl in the corner kept her book open but had stopped turning pages an hour ago. Someone put another log on. The fire accepted it with a crash of sparks, and for a moment the shadows leaned in from every wall, curious, and settled back. It would snow like this, the landlady said, to the room in general, until it forgot how to stop.`,
  ],
  banter: [
    `"You're holding it upside down," Vesimir said, without looking up from his ledger.
"I'm appraising it," Orsala said, rotating the astrolabe anyway. "Gravity is a factor."
"It's a fake."
"Everything in your shop is a fake. That's why I shop here — the prices are honest about it."
He closed the ledger at last. "That piece came from the Palazzo cellar. There's provenance."
"There's a receipt. Provenance is a receipt with a story you liked better." She set the astrolabe down and tapped it once, and something inside it shifted — the faintest celestial click — and they both heard it, and both pretended not to. "Ten crowns."
"Twenty-five, and I'll include the insult for free."
"Twelve, and I'll stop telling people where you get your ink."
They looked at each other across the glass counter, twenty years of exactly this between them, and Vesimir sighed the sigh of a man who has already lost and is merely negotiating the date. "Fourteen."
"Sold," said Orsala, "to the only honest dealer in the city."`,
    `"You're standing in my light."
"Your light. On my stakeout. That's my lamppost, Kell — third from the fountain, mine since the guild split."
"The guild split because you counted the take wrong, and it's a municipal lamppost, you enormous fraud."
"Counted it conservatively," Kell said, "which is what you do when your partner files receipts like a drunk throwing confetti."
Down the boulevard something metal dragged its voice across the cobbles — a slow, long scrape, like the city clearing its throat — and they both went quiet without agreeing to. When it had passed they resumed at a lower volume, the way professionals do.
"Half," Kell said. "Final offer. Plus I never tell the Warden what you keep in the ledger's false spine."
"You can't read the false spine."
"Don't have to. I watched you hide it."
A pause; the fountain did its patient arithmetic behind them. "Sixty-forty," said Kell. "And you buy the coffee until it's over."
"Done," said Fen, "you ridiculous man." They shook hands without looking at each other, which in their language was an embrace.`,
  ],
  dread: [
    `On the third morning the clocks disagreed, which was strange, because the house had never let them. The hall clock said six minutes to midnight; her father's pocket watch, wound every Sunday of her childhood, said noon; the little enamel one in the kitchen had simply stopped, its hands folded like idle wings. Tem stood in the hall in her coat, bag still on her shoulder, keys still in her fist, and listened. The radiator ticked — no. The radiator had been drained since September. She stood very still and let the house be quiet at her, and the quiet had a grain to it now, a direction, the way silence in a forest changes when something with weight is standing downwind. On the stairs above, one step creaked. Not under a foot — the house settling, she told herself, ninety years of settling, entirely normal — but the creak was the fifth step, and the fifth step only ever creaked before the sixth, and no one was coming down, and she knew, with the certainty that arrives a half-second before the evidence, that something was waiting to hear what she would do next.`,
    `The dogs started it, or rather they stopped everything else. At six o'clock every dog in Harrow Lane came out to its gate, sat down in a neat row along the fence line, and faced the field — not sniffing, not barking, just facing it, the way an audience faces an orchestra. Tomasz noticed because his own dog broke a lifelong rule and did not come when called. The field had nothing in it. That was what he told himself: short winter grass, the hedge, the pylon humming its one flat note. It was full dark by the time he walked out with a torch, and the cold had the flat, pressed quality of a held breath. Halfway to the hedge he stopped noticing the cold, because far out, low along the ground where no path had ever been, small lights had come on — arranged in no shape he could name, at a distance they should not have been able to hold, each one perfectly still. And the dogs, behind him, had begun, very softly, all together, to wag their tails.`,
  ],
  intimacy: [
    `The six-forty would come up from the valley in twenty minutes, and they had agreed — firmly, twice, almost in writing — not to make a scene of it. So they had tea in the kitchen at half five, the lamp on, the blue hour standing politely at the window, and neither of them mentioned the suitcase by the door except once, to say it was heavier than it looked. Her ticket stood in her coat pocket like a small rectangular future. He kept nearly saying things. She watched him nearly say them and loved him for the restraint, which was, after all, the thing he was best at, and the worst. "You'll fix the gate," she said. "First thing," he said. The kettle ticked as it cooled. When the sound of the train finally came up through the dark — far off, then nearer, patient as weather — they stood together at the door without needing to, and she picked up the suitcase, and it was, as predicted, heavier than it looked, with everything she wasn't leaving after all.`,
    `The power went out at half past eight, in the middle of his song, and the radio died with a small apologetic click. Sixty years ago the dark had been an invitation; fifty years ago, an inconvenience; now it was simply a guest, and Mozia received it as one, feeling her way to the cupboard where the candles lived and calling toward the parlor that they would manage, thank you, as indeed they always had. He found the matches by touch. The candle, when it caught, returned the room to them in miniature: the two armchairs, the dead radio, forty years of photographs going gold along the mantel. His hip complained; her knees had opinions; and so they danced the way they danced now — hardly moving, his hand at her back, her head where her head went, turning slowly on one small orbit while the candle burned straight and the rain worked at the windows. "The lights will come back," she said, near his collar. "In a minute." "Let them wait," he said. And for a while, they did.`,
  ],
};
